import type { components, paths } from '@generated/management';

export type ManagementPaths = paths;
export type CurrentSessionContract = components['schemas']['CurrentSession'];
export type ManagementProblemContract = components['schemas']['ManagementProblem'];
export type SetupConnectionRequestContract = components['schemas']['SetupConnectionRequest'];
export type SetupRegistrationRequestContract = components['schemas']['SetupRegistrationRequest'];
export type SetupSummaryContract = components['schemas']['SetupSummary'];
export type SetupSummaryListContract = components['schemas']['SetupSummaryList'];
export type SetupConnectionTestContract = components['schemas']['SetupConnectionTest'];
export type SetupDetailsContract = components['schemas']['SetupDetails'];
export type SetupHealthContract = components['schemas']['SetupHealth'];
export type SetupLimitsContract = components['schemas']['SetupLimits'];
export type OverviewContract = components['schemas']['Overview'];
export type NamespaceStatsContract = components['schemas']['NamespaceStats'];
export type AdminPageNamespaceStatsContract = components['schemas']['AdminPageNamespaceStats'];
export type NamespaceExportContract = components['schemas']['NamespaceExport'];
export type NamespaceDetailsContract = components['schemas']['NamespaceDetails'];
export type DatabaseMonitoringContract = components['schemas']['DatabaseMonitoring'];
export type RuntimeMonitoringContract = components['schemas']['RuntimeMonitoring'];
export type ActivityPageContract = components['schemas']['ActivityPage'];
export type TtlStateContract = components['schemas']['TtlState'];
export type ManagementEntryMetadataContract = components['schemas']['ManagementEntryMetadata'];
export type AdminPageManagementEntryMetadataContract = components['schemas']['AdminPageManagementEntryMetadata'];
export type CacheValueContract = components['schemas']['CacheValue'];
export type RevealedEntryValueContract = components['schemas']['RevealedEntryValue'];
